


spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=MDsTailor
    username: sa
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
server:
  port: 8081


