jwt:
  secret: '2X(&X8S[M;@(P2Jp@7$S&NHe=3!?QAk|C:|miE^g7yLZ6hF{]eWRo`mW!Bzr<'

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=MDsTailor
    username: sa
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


